name: JAVA CI
on: push
jobs:
  test:
    runs-on: [ubuntu-latest]
    container: golang:1.19.0
    steps:
      - name: go to backend
        run: bash cd backend
      - name: build backend
        run: go build
      - name: run backend
        run: go run backend
      - name: go back
        run: bash cd ..
      - name: build frontend
        run: go build /usr/local/go/src/simple-fortune-cookie/frontend
      - name: run test
        run: go test /usr/local/go/src/simple-fortune-cookie/frontend
  